[package]
name = "ramp-ds"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
dyn-clone = "1.0.17"
either = "1.13.0"
float-ord = "0.3.2"
ggez = "0.9.3"
glyph_brush = "0.7.11"
log = "0.4.24"
